apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: externaldns

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/kubernetes-sigs/external-dns/refs/heads/master/charts/external-dns/crds/dnsendpoint.yaml
  - github.com/kubernetes-sigs/external-dns/kustomize?ref=v0.19.0
