kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-ingress-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik-ingress-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: traefik-ingress-controller
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: ghcr.io/traefik/traefik:3.3.4
          args:
            - --api.insecure=true
            - --api.dashboard=true
            - --providers.kubernetesingress
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
            - name: dashboard
              containerPort: 8080
