apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# With CRDs
resources:
  - https://raw.githubusercontent.com/traefik/traefik/v3.5.1/docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
  - cluster_role_with_crd.yaml

# Without CRDs
#resources:
#  - cluster_role_no_crd.yaml
